export * as deviceProps from './deviceProps'
export { default as hasProp } from './hasProp'
export { default as log } from './log'
export { default as scrollTo } from './scrollTo'
export { default as wait } from './wait'
