export * as deviceProps from './deviceProps'
export { default as debounce } from './debounce'
export { default as hasProp } from './hasProp'
export { default as log } from './log'
export { default as getElementFromAnchor } from './getElementFromAnchor'
export { default as getNearestPageAnchor } from './getNearestPageAnchor'
export { default as scrollToAnchor } from './scrollToAnchor'
export { default as wait } from './wait'
